version: "3.9"

services:
  postgres-notification:
    image: postgres:alpine
    ports: 
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-okteto-notification:/var/lib/postgresql/data
    
  notifications_service:
    build: .
    restart: always
    ports: 
      - 8000:8000
    depends_on: 
      - postgres-notification

volumes:
  postgres-okteto-notification: