version: "3.9"

services:
  postgres:
    image: postgres:alpine
    ports: 
      - "5435:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-okteto-notification:/var/lib/postgresql/data
    
  notifications_service:
    build: .
    restart: always
    ports: 
      - 8000:8000
    depends_on: 
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "9999:8080"
    depends_on:
      - postgres

volumes:
  postgres-okteto-notification: